### ISSUE TITLE
Improve development process

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/localcast#1]
Currently any changes require you to completely restart nodewebkit. Maybe this can be helped somehow. ("Livelreload")

Maybe this helps:
https://github.com/rogerwang/node-webkit/wiki/Livereload-node-webkit-on-changes

**Comment by normanrz** [comment]
Just hitting the reload button works for me, when editing stuff in the `app` folder.

**Comment by hotzenklotz** [comment]
Found the right reload button :-)
